# Generated by Django 6.1 on 2026-09-07 15:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_stand_slice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standsession',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
